// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwvafztvqwxzcygpeohl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3dmFmenR2cXd4emN5Z3Blb2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTMxODIsImV4cCI6MjA2NzU4OTE4Mn0.IXd0DOdZ7Cx1h6_nlBiiR5YwgtzBiydxqGmraVpi9qI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);